USE [BLOOD_DONATION]
GO

/****** Object:  Table [dbo].[TBL_Donor]    Script Date: 2/20/2021 10:11:12 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TBL_Donor](
	[DonorId] [INT] IDENTITY(1,1) NOT NULL,
	[FirstName] [NVARCHAR](100) NOT NULL,
	[MiddleName] [NVARCHAR](100) NULL,
	[LastName] [NVARCHAR](100) NOT NULL,
	[Gender] [NVARCHAR](50) NOT NULL,
	[BateOfBirth] [DATE] NOT NULL,
	[BloodGroup] [NVARCHAR](100) NOT NULL,
	[Email] [NVARCHAR](100) NOT NULL,
	[PhoneNo] [NVARCHAR](10) NOT NULL,
	[District] [NVARCHAR](100) NOT NULL,
	[Munciplity] [NVARCHAR](100) NOT NULL,
	[City] [NVARCHAR](100) NOT NULL,
	[WardNo] [INT] NOT NULL,
	[CreatedBy] [NVARCHAR](100) NOT NULL,
	[CreatedDate] [DATETIME] NULL,
	[IsActive] [BIT] NULL,
PRIMARY KEY CLUSTERED 
(
	[DonorId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TBL_Donor] ADD  DEFAULT (GETDATE()) FOR [CreatedDate]
GO

ALTER TABLE [dbo].[TBL_Donor] ADD  DEFAULT ('1') FOR [IsActive]
GO


